// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNeTtdhs9ep48rKGL8VA7BndByW_g0F1I',
    appId: '1:466662634867:web:a1da1e8d2efa64a85e8106',
    messagingSenderId: '466662634867',
    projectId: 'quiz-whiz-a7493',
    authDomain: 'quiz-whiz-a7493.firebaseapp.com',
    storageBucket: 'quiz-whiz-a7493.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw0WRtGFpFHqLvHZxo1qDk3BorWPZY-ew',
    appId: '1:466662634867:android:dbb201c2375a36d15e8106',
    messagingSenderId: '466662634867',
    projectId: 'quiz-whiz-a7493',
    storageBucket: 'quiz-whiz-a7493.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxHmlaqSKgPrKgyHVjNZET2tfNqyGLLYc',
    appId: '1:466662634867:ios:302ef3156110433f5e8106',
    messagingSenderId: '466662634867',
    projectId: 'quiz-whiz-a7493',
    storageBucket: 'quiz-whiz-a7493.firebasestorage.app',
    iosBundleId: 'com.example.flashcardProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNeTtdhs9ep48rKGL8VA7BndByW_g0F1I',
    appId: '1:466662634867:web:0a5ab8474e3c0a705e8106',
    messagingSenderId: '466662634867',
    projectId: 'quiz-whiz-a7493',
    authDomain: 'quiz-whiz-a7493.firebaseapp.com',
    storageBucket: 'quiz-whiz-a7493.firebasestorage.app',
  );
}
